#!/usr/bin/env node
/**
 * Renders the shared JSON fixtures (tests/fixtures/*.json) as a psql include for pgTAP, so the
 * database triggers are tested against exactly the inputs the TypeScript domain tests use.
 *
 *   node scripts/fixture-sql.mjs   → writes supabase/tests/_fixtures.psql
 *
 * tests/unit/fixture-sql.test.ts fails if the committed file is out of date.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const OUTPUT = path.join(root, "supabase", "tests", "_fixtures.psql");

const read = (name) => JSON.parse(fs.readFileSync(path.join(root, "tests", "fixtures", name), "utf8"));
const lit = (v) => (typeof v === "number" ? String(v) : `'${String(v).replaceAll("'", "''")}'`);

export function renderFixtureSql() {
  const withdrawal = read("withdrawal.json").cases;
  const cost = read("administration_cost.json").cases;
  const rows = (cases, cols) => cases.map((c) => `  (${cols.map((k) => lit(c[k])).join(", ")})`).join(",\n");
  return `-- GENERATED by scripts/fixture-sql.mjs from tests/fixtures/*.json — do not edit.
-- Included by pgTAP tests with \\ir _fixtures.psql.

create temp table fx_withdrawal (
  n serial, given_at timestamptz, slaughter_withdrawal_days integer, expected_clear_date date
) on commit drop;
insert into fx_withdrawal (given_at, slaughter_withdrawal_days, expected_clear_date) values
${rows(withdrawal, ["given_at", "slaughter_withdrawal_days", "expected_clear_date"])};

create temp table fx_cost (
  n serial, dose_ml numeric, cost_cents integer, size_ml numeric, expected_cost_cents integer
) on commit drop;
insert into fx_cost (dose_ml, cost_cents, size_ml, expected_cost_cents) values
${rows(cost, ["dose_ml", "cost_cents", "size_ml", "expected_cost_cents"])};
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(OUTPUT, renderFixtureSql());
  console.log(`wrote ${path.relative(root, OUTPUT)}`);
}
